### PR TITLE
[optimization] Add loadArray(Array) instead load(Collection)

### PR DESCRIPTION
**Pull request by messi89**
Hi guys,

I added support to load directly an array of arrays or an array of objects (stdClass) from QueryBuilder instead of load collection from Eloquent.

collection->toArray() isn't suitable with big data (more than 10k rows)

I added auto heading from array keys and createHeadingStyle (fluent), you can check the readme

### CODE REVIEW

**Comment by SimoTod** [comment]
Hi @messi89, 
thanks for your PR. I'm sorry for being so late but I didn't see the notification after you had submitted it last November. Unfortunately, I cannot merge your PR right now because it contains breaking changes (You modified the signature of our interfaces) but I'm happy to discuss that with you.
You are forcing people to implement a method even if they don't want to use it.
What problem does your PR want to fix? Loading an array of 100K items need a lot of memory.
Do you had issue with the standard implementation?
Sorry, lots of question but I want to discuss the benefit before introducing a BC.

**Comment by messi89** [comment]
Hi @SimoTod 

the standard implementation use collection->toArray() when we have a lot of row converting a collection to array cost a lot of time

So I change the approch is to use the Query builder (instead of Eloquent) to get an array of objects so no need to convert it to an array (collection->toArray()).

With this change I can import 25k lines (with 17 columns)  from database in 12s (with the standard method need more than 600s)

**Comment by SimoTod** [comment]
Yes, I think it uses $model->toArray(). 
I'm happy to improve the performance but I don't really want to add BC.

We could relax the condition in `/src/Exporter/AbstractSpreadsheet.php` changing `use Illuminate\Database\Eloquent\Collection;`  to `Illuminate\Support\Collection`

and BasicSerialser will become
public function getData($data)
    {
        // YOUR if logic
    }

so the old code will still work and we can use collections of objects/arrays/Models. 

Can you give it a try (please start from the current release and don't add method to the interfaces, submit it as a separate PR) and see how it goes?

Thank you,
Simone

**Comment by SimoTod** [comment]
Hi,

I did a benchmark test with 50K rows and 15 columns on local.
Eloquent: 25s
Array: 9s

There is an improvement, but the standard method is not as slow as you said. 
Can you send me the snippet of code where the package is so slow?

Thank you.

**Comment by SimoTod** [comment]
The package is going to support generic collections and query builder objects. I'm going to tag a release in the next days, This PR is conflicting so I'm going to close it but I wanted to thank you for that idea.

**Pull request closed without merging**
